[workspace]
members = ["crates/*"]

resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
authors = ["Yiyu Lin<linyiyu1992@gmail.com>"]

[workspace.dependencies]
clap = {  version = "4.5", features = ["derive"] }

thiserror = "2"