[package]
name = "svn-repos"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
svn-fs.workspace = true

thiserror.workspace = true
bitflags = { workspace = true }
bytes = { workspace = true }