[package]
name = "svn-ra"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
strum = { workspace = true }
svn-subr.workspace = true

[features]
_sasl = []  # SVN_HAVE_SASL
default = []
