[package]
name = "svn-delta"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
svn-types = { workspace = true }
thiserror = { workspace = true }


indextree = { version = "4.7" }