[package]
name = "svn-wc"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
svn-types.workspace = true
svn-subr = { workspace = true }

rusqlite = { version = "0.36.0", features = ["bundled"] }