[package]
name = "svnlook"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
svn-subr.workspace = true
svn-repos.workspace = true
svn-fs.workspace = true
svn-delta.workspace = true
svn-diff.workspace = true

clap.workspace = true
anyhow.workspace = true