[package]
name = "svn-fs"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
svn-types = { workspace = true }
svn-subr = { workspace = true }

uuid.workspace = true
thiserror = { workspace = true }